packages:
  - "apps/*"
  - "packages/*"
  - "apps/frontend/external/*"
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - "@moonrepo/cli@2.4.5"
  - "@moonrepo/core-linux-arm64-musl@2.4.5"
  - "@moonrepo/core-linux-x64-gnu@2.4.5"
  - "@moonrepo/core-macos-arm64@2.4.5"
  - "@moonrepo/core-macos-x64@2.4.5"
  - "@moonrepo/core-windows-x64-msvc@2.4.5"
